name: Deploy Sphinx documentation to Github pages

on:
  push:
    branches:
      - main

env:
  UV_SYSTEM_PYTHON: 1
  UV_PYTHON_PREFERENCE: system

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.1"

      - name: Install dependencies
        run: uv pip install -e '.[docs]'

      - name: Build docs
        run: sphinx-build docs ./docs/_build/html/

      - uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/_build/html/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
